# Generated by Django 4.0 on 2021-12-15 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=1)),
                ('correct', models.IntegerField()),
                ('wrong', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Sual')),
                ('a', models.CharField(max_length=200, null=True, verbose_name='A)')),
                ('b', models.CharField(max_length=200, null=True, verbose_name='B)')),
                ('c', models.CharField(max_length=200, null=True, verbose_name='C)')),
                ('d', models.CharField(max_length=200, null=True, verbose_name='D)')),
                ('answer', models.CharField(max_length=200, verbose_name='Cavab:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
