# Generated by Django 4.0 on 2021-12-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_makidoin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='makidoin',
        ),
        migrations.RemoveField(
            model_name='resultsmodel',
            name='created_date',
        ),
    ]
